FROM postgres:11.2
ADD data/datasource.csv /docker-entrypoint-initdb.d/ 
ADD db/10_init.sql /docker-entrypoint-initdb.d/
ADD db/20_copy.sql /docker-entrypoint-initdb.d/
RUN chmod a+r /docker-entrypoint-initdb.d/*
EXPOSE 5432